# -*- coding: utf-8 -*-
"""image_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2hVrHWf0m7dDCZxcAZrdzJAOSQsJ-YK
"""

import torch
print(torch.cuda.is_available())

import torch
print(torch.cuda.is_available())

!pip install -U bitsandbytes

from transformers import LlavaForConditionalGeneration, AutoProcessor, BitsAndBytesConfig
import torch

model_id = "llava-hf/llava-1.5-7b-hf"

print("Loading processor...")
processor = AutoProcessor.from_pretrained(model_id)

print("Setting quantization config...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

print("Loading model (this may take 2–5 min)...")
model = LlavaForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

model.eval()

print("Model loaded successfully ✅")

from PIL import Image

def ask_llava(image_path, question):
    image = Image.open(image_path).convert("RGB")

    prompt = f"USER: <image>\n{question}\nASSISTANT:"

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    ).to("cuda")

    output = model.generate(
        **inputs,
        max_new_tokens=100
    )

    answer = processor.decode(output[0], skip_special_tokens=True)

    return answer

from google.colab import files
uploaded = files.upload()

!pip install pymupdf

import fitz

import fitz

def extract_images_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    images = []

    for page_num in range(len(doc)):
        page = doc[page_num]
        img_list = page.get_images(full=True)

        for img_index, img in enumerate(img_list):
            xref = img[0]
            base_image = doc.extract_image(xref)
            image_bytes = base_image["image"]

            image_path = f"image_page{page_num}_img{img_index}.png"
            with open(image_path, "wb") as f:
                f.write(image_bytes)

            images.append({
                "path": image_path,
                "page": page_num + 1,
                "index": img_index
            })

    return images

pdf_path = "baseapeper2.pdf"

images = extract_images_from_pdf(pdf_path)

print("Total images:", len(images))

for i, img in enumerate(images):
    print(i, img)

from PIL import Image

def ask_llava(image_path, question):
    image = Image.open(image_path).convert("RGB")

    prompt = f"USER: <image>\n{question}\nASSISTANT:"

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    ).to("cuda")

    output = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.7
    )

    answer = processor.decode(output[0], skip_special_tokens=True)

    # Clean answer (remove prompt part)
    if "ASSISTANT:" in answer:
        answer = answer.split("ASSISTANT:")[-1].strip()

    return answer

import matplotlib.pyplot as plt

def show_image(image_path):
    img = Image.open(image_path)
    plt.imshow(img)
    plt.axis('off')

selected = images[1]   # try different indexes later

show_image(selected["path"])

question = "Describe the graph in this image."

answer = ask_llava(selected["path"], question)

print("Answer:", answer)

selected = images[1]   # try different indexes later

show_image(selected["path"])

question = "Is the value increasing or decreasing?"

answer = ask_llava(selected["path"], question)

print("Answer:", answer)

def format_output(answer, image_info):
    # simple confidence (heuristic)
    confidence = min(len(answer.split()) / 20, 1.0)

    return {
        "answer": answer,
        "confidence": round(confidence, 2),
        "evidence": {
            "type": "image",
            "page": image_info["page"],
            "image_index": image_info["index"]
        }
    }

selected = images[1]

question = "Describe the graph in this image."

answer = ask_llava(selected["path"], question)

result = format_output(answer, selected)

print(result)

selected = images[1]   # try different indexes later

show_image(selected["path"])

question = "Is the value increasing or decreasing?"

answer = ask_llava(selected["path"], question)

print("Answer:", answer)